/**
 * DAY 14/30
 * Scope
 * https://www.hackerrank.com/challenges/30-scope/
 */

package com.thirtydaysofcode;

import java.util.*;

public class Scope {

    private static class Difference {
        public int maximumDifference = 0;
        private int[] elements;

        public Difference(int[] elements) {
            this.elements = elements;
        }

        public void computeDifference() {
            for (int i = 0; i < elements.length - 1; i++) {
                for (int j = i + 1; j < elements.length; j++) {
                    int difference = Math.abs(elements[i] - elements[j]);
                    if (difference > maximumDifference) {
                        maximumDifference = difference;
                    }
                }
            }
        }
    }

    // Code below this was generated by HackerRank
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        int[] a = new int[n];
        for (int i = 0; i < n; i++) {
            a[i] = sc.nextInt();
        }
        sc.close();

        Difference difference = new Difference(a);

        difference.computeDifference();

        System.out.print(difference.maximumDifference);
    }

}
