package com.thirtydaysofcode.utils;

/**
 * Interface used in some of the challenges.
 * Generated by HackerRank.
 * Used in:
 * - Interfaces
 */
public interface AdvancedArithmetic {

    /**
     * Calculates the sum of all the divisors of the number.
     * @param n integer number
     * @return the sum of all the divisors of the number n.
     */
    int divisorSum(int n);
}
