package com.thirtydaysofcode.utils;

/**
 * Abstract class used in some the challenges.
 * Generated by HackerRank.
 * Used in:
 * - AbstractClasses
 */
public abstract class Book {
    protected String title;
    protected String author;

    public Book(String title, String author) {
        this.title = title;
        this.author = author;
    }

    public abstract void display();
}
