package com.thirtydaysofcode.utils;

/**
 * Node class used in some challenges.
 * Generated by HackerRank.
 * Used in:
 * - LinkedLists
 * - MoreLinkedLists
 * - BSTHeight
 * - BreadthFirstTraversal
 */
public class Node {
    public Node left, right, next;
    public int data;

    public Node(int data) {
        this.data = data;
        left = right = null;
        next = null;
    }
}
