-- Shortest city name
SELECT TOP 1 CITY, LEN(CITY) AS LENGTH
FROM STATION
ORDER BY LENGTH ASC, CITY ASC;

-- Longest city name
SELECT TOP 1 CITY, LEN(CITY) AS LENGTH
FROM STATION
ORDER BY LENGTH DESC, CITY ASC;